version: '3.8'

services:
  server:
    container_name: server
    environment:
      - FLASK_APP=server:create_app()
      - FLASK_DEBUG=1
    volumes:
      - ./backend:/app
    command: flask run --host=0.0.0.0

  worker:
    container_name: worker
    volumes:
      - ./backend:/app

  dashboard:
    container_name: dashboard

  redis:
    container_name: redis

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true